# Generated by Django 4.2 on 2025-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VzNab',
            fields=[
                ('code', models.BigIntegerField(db_comment='код', primary_key=True, serialize=False)),
                ('pkey', models.BigIntegerField(db_comment='Код строки спецификации')),
                ('spc_sign', models.CharField(db_comment='Обозначение спецификации', max_length=100)),
                ('item_sign', models.CharField(db_comment='Обозначение элемента спецификации', max_length=100)),
                ('all9999', models.BigIntegerField(db_comment='Признак -9999')),
                ('pos', models.CharField(blank=True, db_comment='Позиция', max_length=10, null=True)),
                ('cntnum', models.BigIntegerField(db_comment='Количество числитель')),
                ('cntdenom', models.BigIntegerField(db_comment='Количество знаменатель')),
                ('kpr', models.CharField(blank=True, db_comment='Код принадлежности', max_length=5, null=True)),
                ('kdd', models.DateField(blank=True, db_comment='Дата исключения', null=True)),
                ('dvi', models.DateField(blank=True, db_comment='DVI', null=True)),
                ('iz', models.CharField(blank=True, db_comment='IZ', max_length=25, null=True)),
                ('change_mark', models.BigIntegerField(blank=True, db_comment='Код блока замен', null=True)),
                ('spc_color_code', models.BigIntegerField(blank=True, db_comment='Цвет узла', null=True)),
                ('item_sign_old', models.CharField(blank=True, db_comment='Старое обозначение элемента', max_length=100, null=True)),
                ('ndd', models.DateField(blank=True, db_comment='Дата начала', null=True)),
            ],
            options={
                'db_table': 'vz_nab',
                'db_table_comment': 'Импорт спецификаций для витязя (от нас к ним)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VzNorm',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('plcode', models.CharField(max_length=30)),
                ('ko_sign', models.CharField(max_length=100)),
                ('old_ko_sign', models.CharField(max_length=100)),
                ('norm', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('mass', models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True)),
                ('color_code', models.BigIntegerField(blank=True, null=True)),
                ('schema_code', models.BigIntegerField(blank=True, null=True)),
                ('wssign', models.CharField(blank=True, max_length=10, null=True)),
                ('dobjcode', models.BigIntegerField(blank=True, null=True)),
                ('tp2ko2ri', models.BigIntegerField(blank=True, null=True)),
                ('sect_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('sect_code', models.BigIntegerField(blank=True, null=True)),
                ('zagweight', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('zagsize', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'vz_norm',
                'db_table_comment': 'Нормы витязя',
                'managed': False,
            },
        ),
    ]
