# Generated by Django 4.2 on 2025-05-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konstrobj',
            fields=[
                ('unvcode', models.BigIntegerField(db_comment='Уникальный код', primary_key=True, serialize=False)),
                ('itemcode', models.BigIntegerField(db_comment='Код элемента')),
                ('sign', models.CharField(db_comment='Обозначение', max_length=200)),
                ('name', models.CharField(blank=True, db_comment='Наименование', max_length=200, null=True)),
                ('notice', models.CharField(blank=True, db_comment='Примечание', max_length=255, null=True)),
                ('attr', models.BigIntegerField(db_comment='Признак типа')),
                ('supplytype', models.BigIntegerField(db_comment='Признак изготовления')),
                ('owner', models.BigIntegerField(db_comment='Владелец')),
                ('protection', models.BigIntegerField(db_comment='Признак закрытости')),
                ('recdate', models.DateField(db_comment='Дата записи')),
                ('revision', models.BigIntegerField(db_comment='Ревизия')),
                ('planningtype', models.BigIntegerField(db_comment='Тип планирования')),
                ('format', models.CharField(blank=True, db_comment='Формат', max_length=15, null=True)),
                ('formedtype', models.BigIntegerField(blank=True, db_comment='Сформирована как', null=True)),
            ],
            options={
                'db_table': 'konstrobj',
                'db_table_comment': 'Конструкторские объекты',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('code', models.FloatField(db_comment='Код', primary_key=True, serialize=False)),
                ('plcode', models.CharField(blank=True, db_comment='Заводской код', max_length=30, null=True, unique=True)),
                ('okpcode', models.CharField(blank=True, db_comment='Код ОКП', max_length=20, null=True)),
                ('tnvedcode', models.CharField(blank=True, db_comment='Код ТНВЭД', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_comment='Наименование', max_length=255, null=True)),
                ('matname', models.CharField(blank=True, db_comment='Марка', max_length=100, null=True)),
                ('namestd', models.CharField(blank=True, db_comment='Стандарт на марку', max_length=150, null=True)),
                ('profile', models.CharField(blank=True, db_comment='Профиль', max_length=80, null=True)),
                ('profstd', models.CharField(blank=True, db_comment='Стандарт на профиль', max_length=50, null=True)),
                ('tu', models.CharField(blank=True, db_comment='Технические условия', max_length=50, null=True)),
                ('recdate', models.DateField(blank=True, db_comment='Дата записи', null=True)),
                ('notice', models.CharField(blank=True, db_comment='Примечание', max_length=255, null=True)),
                ('ivccode', models.CharField(blank=True, db_comment='Код ИВЦ', max_length=10, null=True)),
                ('ivcgroupcode', models.BigIntegerField(blank=True, db_comment='Код калькуляционной группы ИВЦ', null=True)),
                ('ivcname', models.CharField(blank=True, db_comment='Наименование ИВЦ', max_length=75, null=True)),
                ('profname', models.CharField(blank=True, db_comment='Наименование профиля', max_length=80, null=True)),
                ('gabarit', models.CharField(blank=True, db_comment='Габариты', max_length=50, null=True)),
                ('updatedate', models.DateField(blank=True, db_comment='Дата изменения', null=True)),
                ('density', models.DecimalField(blank=True, db_comment='Плотность', decimal_places=6, max_digits=14, null=True)),
                ('state', models.BigIntegerField(db_comment='Статус материала')),
                ('is_product', models.BigIntegerField(db_comment='Признак продукта')),
                ('mattype', models.BigIntegerField(db_comment='Тип материала')),
            ],
            options={
                'db_table': 'materials',
                'db_table_comment': 'Справочник материалов',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockobj',
            fields=[
                ('code', models.BigIntegerField(db_comment='Код ТМЦ', primary_key=True, serialize=False)),
                ('basecode', models.BigIntegerField(db_comment='Код базовой таблицы')),
                ('basetype', models.BigIntegerField(db_comment='Тип базовой таблицы')),
                ('drmet', models.BigIntegerField(blank=True, db_comment='Признак драгметалла', null=True)),
                ('description', models.CharField(blank=True, db_comment='Описание ТМЦ', max_length=1024, null=True)),
                ('desc_date', models.DateField(blank=True, db_comment='Дата форм. описания', null=True)),
                ('desc_fmt', models.CharField(blank=True, db_comment='Формат описания', max_length=30, null=True)),
                ('subconto_userdate', models.DateField(blank=True, db_comment='Дата изменения субконто', null=True)),
                ('subtype', models.BigIntegerField(blank=True, db_comment='Подтип', null=True)),
                ('notice', models.CharField(blank=True, db_comment='Примечание', max_length=100, null=True)),
                ('recdate', models.DateField(blank=True, db_comment='Дата записи', null=True)),
                ('desc_update_check', models.BigIntegerField()),
                ('sign', models.CharField(blank=True, db_comment='Обозначение', max_length=200, null=True)),
                ('name', models.CharField(blank=True, db_comment='Наименование', max_length=255, null=True)),
                ('unvcode', models.BigIntegerField(blank=True, null=True)),
                ('attr', models.BigIntegerField(blank=True, db_comment='Признак типа КЭ', null=True)),
                ('is_annul', models.BigIntegerField(blank=True, db_comment='Аннулировано', null=True)),
                ('min_leave_value', models.FloatField(blank=True, db_comment='Минимальный отпуск', null=True)),
                ('is_num', models.BigIntegerField(blank=True, db_comment='Номерной объект', null=True)),
                ('mat_state', models.BigIntegerField(blank=True, null=True)),
                ('nomsign', models.CharField(blank=True, max_length=200, null=True)),
                ('params', models.BigIntegerField(blank=True, null=True)),
                ('min_leave_value_deviation', models.FloatField(blank=True, db_comment='Процент отклонения минимального отпуска', null=True)),
                ('tnved_code', models.CharField(blank=True, db_comment='Код ТНВЭД', max_length=255, null=True)),
                ('storage_period', models.BigIntegerField(blank=True, db_comment='Срок хранения (в днях)', null=True)),
                ('expl_term', models.BigIntegerField(blank=True, db_comment='Срок эксплуатации', null=True)),
                ('expl_term_change_date', models.DateField(blank=True, db_comment='Дата последнего изменения срока эксплуатации', null=True)),
                ('gtin', models.CharField(blank=True, db_comment='GTIN', max_length=14, null=True, unique=True)),
            ],
            options={
                'db_table': 'stockobj',
                'db_table_comment': 'Товарно-материальные ценности складского учета',
                'managed': False,
            },
        ),
    ]
