# Generated by Django 4.2.23 on 2025-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega', '0002_konstrobj_materials_stockobj'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissibleSubst',
            fields=[
                ('code', models.IntegerField(db_column='CODE', primary_key=True, serialize=False)),
                ('both_flag', models.IntegerField(db_column='BOTH_FLAG')),
                ('koef', models.IntegerField(db_column='KOEF')),
                ('datefrom', models.DateField(db_column='DATEFROM')),
                ('dateto', models.DateField(blank=True, db_column='DATETO', null=True)),
            ],
            options={
                'db_table': 'ADMISSIBLE_SUBST',
                'db_table_comment': 'Аналоги',
                'managed': False,
            },
        ),
    ]
