# Generated by Django 4.2.23 on 2025-11-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shtrih', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_storage_days', models.IntegerField()),
                ('production_code', models.IntegerField()),
                ('model_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentBans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10)),
                ('order_date', models.DateField()),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=18, null=True)),
                ('shift', models.CharField(blank=True, max_length=3, null=True)),
                ('assembly_date_from', models.DateField(blank=True, null=True)),
                ('assembly_date_to', models.DateField(blank=True, null=True)),
                ('pakaging_date_from', models.DateField(blank=True, null=True)),
                ('pakaging_date_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apply_to_belarus', models.BooleanField()),
                ('color_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.colors')),
                ('model_name_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.modelnames')),
                ('module_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.modules')),
                ('production_code_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.production_codes')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
