# Generated by Django 4.2.28 on 2026-06-03 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
