# Generated by Django 4.2 on 2025-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentbans',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shipmentbans',
            name='production_code',
        ),
        migrations.RemoveField(
            model_name='shipmentbans',
            name='type_of_work_id',
        ),
        migrations.RemoveField(
            model_name='shipmentbans',
            name='work_end_date',
        ),
        migrations.RemoveField(
            model_name='shipmentbans',
            name='work_start_date',
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='assembly_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='assembly_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='barcode',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='pakaging_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='pakaging_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='production_code_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='shift',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
