# Generated by Django 4.2 on 2025-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0002_remove_shipmentbans_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentbans',
            name='color_code',
        ),
        migrations.AddField(
            model_name='shipmentbans',
            name='color_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
