# Generated by Django 4.2.28 on 2026-06-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0002_shipmentbans_created_at_shipmentbans_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentbans',
            name='assembly_date_from',
        ),
        migrations.RemoveField(
            model_name='shipmentbans',
            name='assembly_date_to',
        ),
    ]
