# Generated by Django 4.2 on 2025-04-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0004_alter_shipmentbans_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentbans',
            old_name='model_id',
            new_name='model_name_id',
        ),
    ]
