# Generated by Django 4.2 on 2025-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0005_rename_model_id_shipmentbans_model_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentbans',
            name='color_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
