# Generated by Django 4.2 on 2025-05-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0005_modelcolors'),
        ('sgp', '0006_alter_shipmentbans_color_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentbans',
            name='production_code_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.production_codes'),
        ),
    ]
