# Generated by Django 4.2 on 2025-05-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0005_modelcolors'),
        ('sgp', '0007_alter_shipmentbans_production_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentbans',
            name='color_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.colors'),
        ),
        migrations.AlterField(
            model_name='shipmentbans',
            name='model_name_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.modelnames'),
        ),
        migrations.AlterField(
            model_name='shipmentbans',
            name='module_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.modules'),
        ),
    ]
