# Generated by Django 4.2 on 2025-03-19 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declaration', '0003_g44'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cleared', models.BooleanField()),
                ('ttn', models.CharField(blank=True, max_length=20, null=True)),
                ('series', models.CharField(blank=True, max_length=10, null=True)),
                ('recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_shipped', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('date_cleared', models.DateField(blank=True, null=True)),
                ('date_payments', models.DateTimeField()),
                ('date_calc', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClearedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('clearance_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_items', to='sez.clearanceinvoice')),
                ('declared_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_items', to='declaration.declareditem')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceInvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('clearance_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_invoice_items', to='sez.clearanceinvoice')),
                ('declared_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_invoice_items', to='declaration.declareditem')),
            ],
        ),
    ]
