# Generated by Django 4.2.23 on 2025-11-24 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrival', '0001_initial'),
        ('shtrih', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cleared', models.BooleanField()),
                ('ttn', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('date_payments', models.DateTimeField(blank=True, null=True)),
                ('date_calc', models.DateTimeField(blank=True, null=True)),
                ('is_gifted', models.BooleanField(default=False)),
                ('only_panel', models.BooleanField(default=False)),
                ('order', models.ManyToManyField(blank=True, to='arrival.order')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceInvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('clearance_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_invoice_items', to='sez.clearanceinvoice')),
                ('declared_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_invoice_items', to='declaration.declareditem')),
                ('model_name_id', models.ForeignKey(blank=True, db_column='model_name_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_invoice_items', to='shtrih.modelnames')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InnerTTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(blank=True, max_length=100, null=True)),
                ('trailer', models.CharField(blank=True, max_length=100, null=True)),
                ('waybill', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.CharField(blank=True, max_length=20, null=True)),
                ('shipper_unp', models.CharField(max_length=20)),
                ('consignee_unp', models.CharField(max_length=20)),
                ('customer_unp', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=200)),
                ('shipper', models.CharField(max_length=200)),
                ('consignee', models.CharField(max_length=200)),
                ('document', models.CharField(max_length=200)),
                ('load', models.CharField(max_length=200)),
                ('unload', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('notice', models.CharField(max_length=200)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InnerTTNItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price_pcs', models.DecimalField(decimal_places=2, max_digits=19)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=19)),
                ('nds', models.PositiveIntegerField(default=0)),
                ('release', models.BooleanField(default=False)),
                ('notice', models.TextField(blank=True, null=True)),
                ('inner_ttn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sez.innerttn')),
                ('model_name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shtrih.modelnames')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClearedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('clearance_invoice_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_items', to='sez.clearanceinvoiceitems')),
                ('declared_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_items', to='declaration.declareditem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceUncleared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('request_quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('uncleared_quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_results', to='sez.clearanceinvoiceitems')),
            ],
            options={
                'verbose_name': 'Результат полной очистки',
                'verbose_name_plural': 'Результаты полной очистки',
            },
        ),
    ]
