# Generated by Django 4.2.23 on 2025-11-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerttnitems',
            name='weight_brutto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
    ]
