# Generated by Django 4.2.20 on 2025-04-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0002_alter_clearanceinvoice_date_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearanceinvoice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='clearanceinvoiceitems',
            options={'ordering': ['id']},
        ),
    ]
