# Generated by Django 4.2.23 on 2025-12-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0002_innerttnitems_weight_brutto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinvoiceitems',
            name='declared_item',
        ),
    ]
