# Generated by Django 4.2 on 2025-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0003_alter_clearanceinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceinvoiceitems',
            name='model_id',
            field=models.IntegerField(),
        ),
    ]
