# Generated by Django 4.2.23 on 2025-12-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0003_remove_clearanceinvoiceitems_declared_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleareditem',
            name='is_hand',
            field=models.BooleanField(default=False),
        ),
    ]
