# Generated by Django 4.2 on 2025-04-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0004_alter_clearanceinvoiceitems_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinvoiceitems',
            name='model_id',
        ),
        migrations.AddField(
            model_name='clearanceinvoiceitems',
            name='model_name_id',
            field=models.IntegerField(default=569),
            preserve_default=False,
        ),
    ]
