# Generated by Django 4.2.23 on 2025-12-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0004_cleareditem_is_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerttnitems',
            name='cargo_space',
            field=models.IntegerField(default=1),
        ),
    ]
