# Generated by Django 4.2.20 on 2025-05-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0005_remove_clearanceinvoiceitems_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceinvoiceitems',
            name='model_unv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
