# Generated by Django 4.2.20 on 2025-05-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0008_restore_model_name_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearanceinvoiceitems',
            old_name='model_name',
            new_name='model_name_id',
        ),
    ]
