# Generated by Django 4.2.20 on 2025-05-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0005_modelcolors'),
        ('sez', '0009_rename_model_name_clearanceinvoiceitems_model_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinvoiceitems',
            name='model_unv',
        ),
        migrations.CreateModel(
            name='ClearanceInvoiceItemModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_links', to='sez.clearanceinvoiceitems')),
                ('model', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item_links', to='shtrih.models')),
            ],
            options={
                'db_table': 'clearance_invoice_item_models',
                'unique_together': {('clearance_invoice_item', 'model')},
            },
        ),
        migrations.AddField(
            model_name='clearanceinvoiceitems',
            name='models_unv',
            field=models.ManyToManyField(related_name='clearance_invoice_items', through='sez.ClearanceInvoiceItemModels', to='shtrih.models'),
        ),
    ]
