# Generated by Django 4.2 on 2025-05-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0010_remove_clearanceinvoiceitems_model_unv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerTTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_unp', models.CharField(max_length=20)),
                ('consignee_unp', models.CharField(max_length=20)),
                ('customer_unp', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=200)),
                ('shipper', models.CharField(max_length=200)),
                ('consignee', models.CharField(max_length=200)),
                ('document', models.CharField(max_length=200)),
                ('load', models.CharField(max_length=200)),
                ('unload', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('notice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InnerTTNItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('measure', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price_pcs', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('inner_ttn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sez.innerttn')),
            ],
        ),
    ]
