# Generated by Django 4.2 on 2025-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0011_innerttn_innerttnitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innerttnitems',
            name='price_pcs',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
