# Generated by Django 4.2 on 2025-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0012_alter_innerttnitems_price_pcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innerttnitems',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
    ]
