# Generated by Django 4.2.20 on 2025-05-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0013_alter_innerttnitems_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleareditem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='innerttn',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='innerttnitems',
            options={'ordering': ['id']},
        ),
    ]
