# Generated by Django 4.2 on 2025-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0014_alter_cleareditem_options_alter_innerttn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerttn',
            name='user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innerttn',
            name='uuid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
