# Generated by Django 4.2 on 2025-05-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0005_modelcolors'),
        ('sez', '0015_innerttn_user_innerttn_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innerttnitems',
            name='item_name',
        ),
        migrations.AddField(
            model_name='innerttnitems',
            name='model_name',
            field=models.ForeignKey(db_constraint=False, default=200, on_delete=django.db.models.deletion.CASCADE, to='shtrih.modelnames'),
        ),
    ]
