# Generated by Django 4.2 on 2025-05-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0017_alter_innerttnitems_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innerttn',
            old_name='user',
            new_name='used',
        ),
    ]
