# Generated by Django 4.2.20 on 2025-05-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0018_rename_user_innerttn_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearanceinvoiceitems',
            old_name='models_unv',
            new_name='models',
        ),
    ]
