# Generated by Django 4.2 on 2025-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0019_rename_models_unv_clearanceinvoiceitems_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerttn',
            name='car',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='innerttn',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='innerttn',
            name='trailer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='innerttn',
            name='waybill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='innerttnitems',
            name='nds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='innerttnitems',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
