# Generated by Django 4.2.20 on 2025-05-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0020_innerttn_car_innerttn_driver_innerttn_trailer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('request_quantity', models.IntegerField()),
                ('uncleared_quantity', models.IntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_results', to='sez.clearanceinvoiceitems')),
            ],
            options={
                'verbose_name': 'Результат полной очистки',
                'verbose_name_plural': 'Результаты полной очистки',
            },
        ),
    ]
