# Generated by Django 4.2 on 2025-05-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0021_clearanceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerttnitems',
            name='release',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
