# Generated by Django 4.2 on 2025-05-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0022_alter_clearanceresult_request_quantity_and_more'),
        ('sez', '0022_innerttnitems_release'),
    ]

    operations = [
    ]
