# Generated by Django 4.2.20 on 2025-05-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0024_alter_innerttnitems_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinvoice',
            name='date_cleared',
        ),
    ]
