# Generated by Django 4.2.20 on 2025-06-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0025_remove_clearanceinvoice_date_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleareditem',
            name='clearance_invoice_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_items', to='sez.clearanceinvoiceitems'),
        ),
    ]
