# Generated by Django 4.2.23 on 2025-10-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0026_cleareditem_clearance_invoice_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClearanceResult',
            new_name='ClearanceUncleared',
        ),
        migrations.RemoveField(
            model_name='clearanceinvoiceitems',
            name='models',
        ),
        migrations.RemoveField(
            model_name='cleareditem',
            name='clearance_invoice',
        ),
        migrations.RemoveField(
            model_name='cleareditem',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='ClearanceInvoiceItemModels',
        ),
    ]
