# Generated by Django 4.2.23 on 2025-10-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0027_rename_clearanceresult_clearanceuncleared_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceuncleared',
            name='comment',
        ),
    ]
