# Generated by Django 4.2.23 on 2025-10-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0014_alter_order_name'),
        ('sez', '0028_remove_clearanceuncleared_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceinvoice',
            name='is_gifted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearanceinvoice',
            name='only_panel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearanceinvoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arrival.order'),
        ),
    ]
