# Generated by Django 4.2.23 on 2025-11-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0014_alter_order_name'),
        ('sez', '0029_clearanceinvoice_is_gifted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinvoice',
            name='order',
        ),
        migrations.AddField(
            model_name='clearanceinvoice',
            name='order',
            field=models.ManyToManyField(blank=True, to='arrival.order'),
        ),
    ]
