# Generated by Django 4.2.23 on 2025-11-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0030_remove_clearanceinvoice_order_clearanceinvoice_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinvoice',
            name='quantity_shipped',
        ),
    ]
