# Generated by Django 4.2.23 on 2025-11-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sez', '0031_remove_clearanceinvoice_quantity_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinvoice',
            name='series',
        ),
    ]
