# Generated by Django 4.2.23 on 2025-11-06 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sez', '0032_remove_clearanceinvoice_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceinvoice',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
