# Generated by Django 4.2 on 2025-02-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('suppose_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='Created', max_length=20)),
                ('invoice', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=3)),
                ('sender', models.CharField(max_length=38)),
                ('sender_address', models.CharField(max_length=250)),
                ('delivery_terms', models.CharField(max_length=3)),
                ('item_count', models.IntegerField()),
                ('receiver', models.CharField(max_length=38)),
                ('receiver_address', models.CharField(max_length=250)),
                ('sender_country_code', models.CharField(max_length=3)),
                ('sender_alpha_country_code', models.CharField(max_length=2)),
                ('g15A_1', models.CharField(max_length=4)),
                ('payment_currency_code', models.CharField(max_length=3)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency_rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('foreign_economic_code', models.CharField(max_length=2)),
                ('payment_type_code', models.CharField(max_length=3)),
                ('provision_date', models.DateField()),
                ('paid_payment_details_count', models.SmallIntegerField()),
                ('declaration_id', models.IntegerField()),
                ('declaration_number', models.CharField(max_length=18)),
                ('permit_number', models.CharField(max_length=23)),
                ('country_name', models.CharField(max_length=17)),
                ('declarant_position', models.CharField(max_length=250)),
                ('declarant_FIO', models.CharField(max_length=250)),
                ('document_id', models.CharField(max_length=36)),
                ('sender_country_name', models.CharField(max_length=17)),
                ('outgoing_number', models.CharField(max_length=50)),
                ('dollar_rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('euro_rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('declaration_date', models.DateField()),
                ('permit_code', models.CharField(max_length=3)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arrival.order')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shot_name', models.CharField(max_length=30)),
                ('count', models.PositiveIntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrival.container')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='container',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arrival.order'),
        ),
    ]
