# Generated by Django 4.2 on 2025-02-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='order',
        ),
        migrations.AddField(
            model_name='declaration',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arrival.container'),
        ),
    ]
