# Generated by Django 4.2 on 2025-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='declaration_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
