# Generated by Django 4.2.20 on 2025-03-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declaration', '0001_initial'),
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleareditem',
            name='declared_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_items', to='declaration.declareditem'),
        ),
        migrations.AddField(
            model_name='clearanceinvoiceitems',
            name='clearance_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_invoice_items', to='arrival.clearanceinvoice'),
        ),
        migrations.AddField(
            model_name='clearanceinvoiceitems',
            name='declared_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_invoice_items', to='declaration.declareditem'),
        ),
    ]
