# Generated by Django 4.2 on 2025-02-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declaration',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='DeclaredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ordinal_number', models.IntegerField()),
                ('country_code', models.CharField(max_length=3)),
                ('alpha_country_code', models.CharField(max_length=3)),
                ('gross_weight', models.FloatField()),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit_code', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('statistical_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('payment_details_count', models.IntegerField()),
                ('document_details_count', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=17)),
                ('g37', models.CharField(max_length=2)),
                ('net_weight', models.FloatField()),
                ('previous_customs_regime_code', models.CharField(max_length=2)),
                ('g373', models.CharField(max_length=3)),
                ('customs_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('g31stz', models.CharField(max_length=50)),
                ('g311stz', models.CharField(max_length=3)),
                ('g312STZ', models.CharField(max_length=13)),
                ('valuation_method', models.CharField(max_length=2)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declared_items', to='arrival.declaration')),
            ],
        ),
    ]
