# Generated by Django 4.2 on 2025-02-26 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cleared', models.IntegerField()),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('date_payments', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClearedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('clearance_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleared_items', to='arrival.clearanceinvoice')),
                ('declared_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_items', to='arrival.declareditem')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceInvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('clearance_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_invoice_items', to='arrival.clearanceinvoice')),
                ('declared_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_invoice_items', to='arrival.declareditem')),
            ],
        ),
    ]
