# Generated by Django 4.2 on 2025-02-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0002_declaration_declaration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='provision_date',
            field=models.DateField(),
        ),
    ]
