# Generated by Django 4.2 on 2025-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0002_alter_declaration_options_declareditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.IntegerField(unique=True),
        ),
    ]
