# Generated by Django 4.2 on 2025-03-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0002_clearanceinvoice_cleareditem_clearanceinvoiceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceinvoice',
            name='date_calc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceinvoice',
            name='date_cleared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceinvoice',
            name='quantity_shipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clearanceinvoice',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clearanceinvoice',
            name='series',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clearanceinvoice',
            name='ttn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clearanceinvoiceitems',
            name='actual_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clearanceinvoiceitems',
            name='model_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clearanceinvoiceitems',
            name='model_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceinvoice',
            name='cleared',
            field=models.BooleanField(),
        ),
    ]
