# Generated by Django 4.2 on 2025-03-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='shot_name',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='container',
            name='load_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
