# Generated by Django 4.2 on 2025-02-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0003_alter_declaration_declaration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='declareditem',
            name='declaration_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='declared_items', to='arrival.declaration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declareditem',
            name='declaration',
            field=models.IntegerField(),
        ),
    ]
