# Generated by Django 4.2 on 2025-03-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0003_rename_shot_name_content_short_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceinvoiceitems',
            name='clearance_invoice',
        ),
        migrations.RemoveField(
            model_name='clearanceinvoiceitems',
            name='declared_item',
        ),
        migrations.RemoveField(
            model_name='cleareditem',
            name='clearance_invoice',
        ),
        migrations.RemoveField(
            model_name='cleareditem',
            name='declared_item_id',
        ),
        migrations.DeleteModel(
            name='ClearanceInvoice',
        ),
        migrations.DeleteModel(
            name='ClearanceInvoiceItems',
        ),
        migrations.DeleteModel(
            name='ClearedItem',
        ),
    ]
