# Generated by Django 4.2 on 2025-02-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0003_alter_container_order_alter_declaration_container'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declareditem',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='declareditem',
            name='declaration_id',
        ),
        migrations.AlterField(
            model_name='container',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='arrival.order'),
        ),
        migrations.AlterField(
            model_name='content',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='arrival.container'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='arrival.container'),
        ),
        migrations.AlterField(
            model_name='declareditem',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declared_items', to='arrival.declaration'),
        ),
    ]
