# Generated by Django 4.2 on 2025-02-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0002_container_alter_order_options_content_and_more'),
        ('arrival', '0003_alter_declaration_declaration_date_and_more'),
    ]

    operations = [
    ]
