# Generated by Django 4.2 on 2025-02-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0004_merge_20250206_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declaration',
            options={'ordering': ['-id']},
        ),
    ]
