# Generated by Django 4.2.20 on 2025-03-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0004_remove_container_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='container',
        ),
        migrations.RemoveField(
            model_name='declareditem',
            name='declaration',
        ),
    ]
