# Generated by Django 4.2 on 2025-03-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0004_remove_clearanceinvoiceitems_clearance_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='suppose_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
