# Generated by Django 4.2 on 2025-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0005_alter_container_exit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='content',
            name='short_name',
            field=models.CharField(max_length=300),
        ),
    ]
