# Generated by Django 4.2.20 on 2025-03-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0005_remove_declaration_container_and_more'),
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceinvoiceitems',
            name='declared_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_invoice_items', to='declaration.declareditem'),
        ),
        migrations.AlterField(
            model_name='cleareditem',
            name='declared_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_items', to='declaration.declareditem'),
        ),
        migrations.DeleteModel(
            name='Declaration',
        ),
        migrations.DeleteModel(
            name='DeclaredItem',
        ),
    ]
