# Generated by Django 4.2 on 2025-06-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0007_lot_container_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('panel', models.PositiveIntegerField()),
                ('skd', models.PositiveIntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrival.lot')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
