# Generated by Django 4.2 on 2025-06-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0008_lotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='makeup/')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrival.lot')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
