# Generated by Django 4.2 on 2025-06-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0009_makeup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeup',
            name='file',
        ),
        migrations.RemoveField(
            model_name='makeup',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='makeup',
            name='lot',
        ),
        migrations.AddField(
            model_name='makeup',
            name='file1',
            field=models.FileField(default=0, upload_to='makeup/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makeup',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='makeup/'),
        ),
        migrations.AddField(
            model_name='makeup',
            name='filename1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makeup',
            name='filename2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrival.order'),
            preserve_default=False,
        ),
    ]
