# Generated by Django 4.2 on 2025-06-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0010_remove_makeup_file_remove_makeup_filename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makeup',
            old_name='file1',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='makeup',
            old_name='filename1',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='makeup',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='makeup',
            name='filename2',
        ),
    ]
