# Generated by Django 4.2 on 2025-06-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0011_rename_file1_makeup_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeup',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
