# Generated by Django 4.2.23 on 2025-12-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declare', models.BooleanField(default=False)),
                ('decl_invoice', models.BooleanField(default=False)),
                ('decl_upload', models.BooleanField(default=False)),
                ('sgp', models.BooleanField(default=False)),
                ('sez', models.BooleanField(default=False)),
                ('sez_calc', models.BooleanField(default=False)),
                ('sez_dbf_download', models.BooleanField(default=False)),
            ],
        ),
    ]
