# Generated by Django 4.2.20 on 2025-05-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_addtitle_addbody'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addbody',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='addtitle',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='visits',
            options={'ordering': ['-id']},
        ),
    ]
