# Generated by Django 4.2 on 2025-06-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_addbody_options_alter_addtitle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addbody',
            options={'ordering': ['-id']},
        ),
    ]
