# Generated by Django 4.2.23 on 2026-02-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=18)),
                ('state', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('color_id', models.ForeignKey(db_column='color_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shtrih.colors')),
                ('model', models.ForeignKey(db_column='model_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shtrih.models')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
