# Generated by Django 4.2.23 on 2026-02-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0001_initial'),
        ('warehouse', '0002_oldproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldproduct',
            name='color_id',
            field=models.ForeignKey(blank=True, db_column='color_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='shtrih.colors'),
        ),
    ]
