# Generated by Django 4.2.28 on 2026-04-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0002_remove_onecttnitem_name_onecttnitem_model'),
        ('shtrih', '0002_scoreboardview'),
        ('warehouse', '0003_alter_oldproduct_color_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehousedo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='warehousedo',
            name='warehouse_product',
        ),
        migrations.RemoveField(
            model_name='warehousettn',
            name='pallet',
        ),
        migrations.AddField(
            model_name='pallet',
            name='ttn_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousettn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousedo',
            name='old_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.oldproduct'),
        ),
        migrations.AddField(
            model_name='warehousedo',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='shtrih.products'),
        ),
        migrations.AddField(
            model_name='warehousettn',
            name='onec_ttn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='onec.onecttn'),
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='WarehouseProduct',
        ),
    ]
