# Generated by Django 4.2.28 on 2026-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_warehouseproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldproduct',
            name='is_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehousedo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
