# Generated by Django 4.2.28 on 2026-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_oldproduct_is_shipment_warehousedo_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseaction',
            name='operation',
            field=models.CharField(default='+', max_length=2),
        ),
    ]
