# Generated by Django 4.2.28 on 2026-05-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0002_scoreboardview'),
        ('warehouse', '0006_warehouseaction_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodlessProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shtrih.colors')),
                ('model_name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='shtrih.modelnames')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BarcodlessDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.barcodlessproducts')),
                ('warehouse_ttn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousettn')),
            ],
        ),
    ]
