# Generated by Django 4.2.28 on 2026-05-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_barcodlessproducts_barcodlessdo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcodlessdo',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='barcodlessdo',
            old_name='product',
            new_name='barcodless_product',
        ),
    ]
