# Generated by Django 4.2.28 on 2026-05-08 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_barcodlessdo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodlessdo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodlessdo',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
