# Generated by Django 4.2.28 on 2026-05-26 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shtrih', '0003_duplicates_shtrihuser_valuable_components'),
        ('warehouse', '0009_barcodlessdo_create_at_barcodlessdo_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_date', models.DateTimeField(auto_now_add=True)),
                ('solve_date', models.DateTimeField(blank=True, null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='shtrih.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
