# Generated by Django 4.2.28 on 2026-06-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0003_duplicates_shtrihuser_valuable_components'),
        ('warehouse', '0010_notpackaging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notpackaging',
            old_name='user',
            new_name='bloom_user',
        ),
        migrations.AddField(
            model_name='notpackaging',
            name='factory_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='shtrih.shtrihuser'),
        ),
    ]
