# Generated by Django 4.2.28 on 2026-06-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shtrih', '0003_duplicates_shtrihuser_valuable_components'),
        ('warehouse', '0011_rename_user_notpackaging_bloom_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notpackaging',
            name='bloom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notpackaging',
            name='factory_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='shtrih.shtrihuser'),
        ),
        migrations.AlterField(
            model_name='notpackaging',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shtrih.products'),
        ),
        migrations.AlterField(
            model_name='notpackaging',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
    ]
