# Generated by Django 4.2.28 on 2026-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_alter_notpackaging_bloom_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouseaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehousettn',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
