# Generated by Django 4.2.28 on 2026-10-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0003_duplicates_shtrihuser_valuable_components'),
        ('warehouse', '0013_pallet_is_deleted_warehouseaction_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousedo',
            name='old_product',
        ),
        migrations.AlterField(
            model_name='warehousedo',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='shtrih.products'),
        ),
        migrations.DeleteModel(
            name='OldProduct',
        ),
    ]
