# Generated by Django 4.2 on 2025-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
