# Generated by Django 4.2 on 2025-02-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departmant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
