# Generated by Django 4.2 on 2025-02-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_departmant_user_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userroles',
            options={'ordering': ['id']},
        ),
    ]
