# Generated by Django 4.2 on 2025-02-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_departmant_user_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userroles',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
