# Generated by Django 4.2.23 on 2025-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStorage',
            fields=[
                ('model_name_id', models.IntegerField(db_column='model_name_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uncleared', models.IntegerField()),
                ('cleared', models.IntegerField()),
                ('simple', models.IntegerField()),
                ('compensation', models.IntegerField()),
            ],
            options={
                'db_table': 'report_storage',
                'ordering': ['model_name_id'],
                'managed': False,
            },
        ),
    ]
