# Generated by Django 4.2.23 on 2026-02-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0002_scoreboardview'),
        ('sreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=1)),
                ('month_count', models.PositiveIntegerField()),
                ('day_count', models.PositiveIntegerField()),
                ('module', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shtrih.modules')),
            ],
            options={
                'ordering': ['module'],
                'unique_together': {('module', 'shift')},
            },
        ),
    ]
