# Generated by Django 4.2.28 on 2026-03-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0002_scoreboardview'),
        ('sreport', '0002_productplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productplan',
            name='workplace',
            field=models.ForeignKey(db_constraint=False, default=10, on_delete=django.db.models.deletion.CASCADE, to='shtrih.workplaces'),
            preserve_default=False,
        ),
    ]
