# Generated by Django 4.2.28 on 2026-03-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sreport', '0003_alter_productplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productplan',
            index=models.Index(fields=['module', 'shift', 'workplace'], name='sreport_pro_module__7b7670_idx'),
        ),
        migrations.AddConstraint(
            model_name='productplan',
            constraint=models.UniqueConstraint(fields=('module', 'shift', 'workplace'), name='unique_module_shift_workplace'),
        ),
    ]
