# Generated by Django 4.2.28 on 2026-03-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sreport', '0004_productplan_sreport_pro_module__7b7670_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productplan',
            name='unique_module_shift_workplace',
        ),
        migrations.RemoveIndex(
            model_name='productplan',
            name='sreport_pro_module__7b7670_idx',
        ),
    ]
