# Generated by Django 4.2.28 on 2026-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sreport', '0005_remove_productplan_unique_module_shift_workplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneCTTNItemScanedCount',
            fields=[
                ('onec_ttn_item_id', models.BigIntegerField(db_column='one_C_ttn_item_id', primary_key=True, serialize=False)),
                ('onec_ttn_number', models.CharField(db_column='number', max_length=50)),
                ('onec_ttn_series', models.CharField(db_column='series', max_length=50)),
                ('model_name_id', models.IntegerField(db_column='model_name_id')),
                ('full_name', models.CharField(db_column='full_name', max_length=100)),
                ('color_id', models.IntegerField(blank=True, db_column='color_id', null=True)),
                ('color_code', models.CharField(blank=True, db_column='color_code', max_length=4, null=True)),
                ('count', models.IntegerField(db_column='count')),
                ('warehouse_warehouse_id', models.BigIntegerField(db_column='warehouse_warehouse_id')),
                ('warehouse_name', models.CharField(db_column='warehouse_name', max_length=100)),
                ('scanned', models.IntegerField(blank=True, db_column='scanned', null=True)),
            ],
            options={
                'db_table': 'onec_onecttnitem_with_scanned_count',
                'ordering': ['onec_ttn_item_id'],
                'managed': False,
            },
        ),
    ]
