# Generated by Django 4.2.28 on 2026-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sreport', '0006_onecttnitemscanedcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTTNBarcode',
            fields=[
                ('product_id', models.IntegerField(db_column='product_id', primary_key=True, serialize=False)),
                ('product_barcode', models.CharField(db_column='product_barcode', max_length=18)),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('user_fio', models.CharField(blank=True, db_column='user_fio', max_length=255, null=True)),
                ('model_name_id', models.IntegerField(db_column='model_name_id')),
                ('model_name_name', models.CharField(db_column='model_name_name', max_length=100)),
                ('warehouse_id', models.IntegerField(db_column='warehouse_id')),
                ('warehouse_name', models.CharField(db_column='warehouse_name', max_length=100)),
                ('warehouse_do_create_at', models.DateTimeField(db_column='warehouse_do_create_at')),
                ('warehouse_ttn_ttn_number', models.CharField(db_column='warehouse_ttn_ttn_number', max_length=50)),
                ('onec_number', models.CharField(db_column='onec_number', max_length=50)),
                ('onec_series', models.CharField(db_column='onec_series', max_length=50)),
            ],
            options={
                'db_table': 'warehouse_ttn_barcode',
                'ordering': ['product_id'],
                'managed': False,
            },
        ),
    ]
