# Generated by Django 4.2.28 on 2026-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sreport', '0007_warehousettnbarcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseMonthModelCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_column='name', max_length=100)),
                ('month1', models.IntegerField(db_column='month1')),
                ('month2', models.IntegerField(db_column='month2')),
                ('month3', models.IntegerField(db_column='month3')),
                ('month4', models.IntegerField(db_column='month4')),
                ('month5', models.IntegerField(db_column='month5')),
                ('month6', models.IntegerField(db_column='month6')),
                ('month7', models.IntegerField(db_column='month7')),
                ('month8', models.IntegerField(db_column='month8')),
                ('month9', models.IntegerField(db_column='month9')),
                ('month10', models.IntegerField(db_column='month10')),
                ('month11', models.IntegerField(db_column='month11')),
                ('month12', models.IntegerField(db_column='month12')),
                ('month24', models.IntegerField(db_column='month24')),
                ('month_more', models.IntegerField(db_column='month_more')),
            ],
            options={
                'db_table': 'warehouse_month_count',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
