# Generated by Django 4.2.28 on 2026-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sreport', '0009_monthproductplan_yearproductplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreboardDayCount',
            fields=[
                ('work_date', models.DateField(db_column='work_date', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity')),
            ],
            options={
                'db_table': 'scoreboard_day_count',
                'ordering': ['work_date'],
                'managed': False,
            },
        ),
    ]
