# Generated by Django 4.2 on 2025-03-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrival', '0004_remove_container_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('recipient', models.CharField(max_length=200)),
                ('shipper', models.CharField(blank=True, max_length=200, null=True)),
                ('seller', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer', models.CharField(max_length=200)),
                ('terms', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arrival.container')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('description_en', models.CharField(max_length=200)),
                ('description_ru', models.CharField(max_length=200)),
                ('measurements', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('packages', models.IntegerField()),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_pcs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
