# Generated by Django 4.2.23 on 2025-11-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('prev_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrival.lot')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('sheet', models.CharField(blank=True, max_length=50, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arrival.container')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
