# Generated by Django 4.2 on 2025-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoiceitem_currency_invoice_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='packages',
        ),
        migrations.AddField(
            model_name='invoice',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='packages',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
