# Generated by Django 4.2 on 2025-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoiceitem_packages_invoice_freight_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipper',
            field=models.TextField(blank=True, null=True),
        ),
    ]
