# Generated by Django 4.2 on 2025-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_buyer_alter_invoice_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='parts_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
