# Generated by Django 4.2 on 2025-05-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_parts_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='parts_for',
            new_name='model',
        ),
    ]
