# Generated by Django 4.2 on 2025-05-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_rename_parts_for_invoice_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['model']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='model',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
