# Generated by Django 4.2 on 2025-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='net_weight',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price_amount',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price_pcs',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
