# Generated by Django 4.2 on 2025-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoiceitem_gross_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price_amount',
            field=models.DecimalField(decimal_places=5, max_digits=24),
        ),
    ]
