# Generated by Django 4.2 on 2025-06-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoiceitem_price_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=5, max_digits=24),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='net_weight',
            field=models.DecimalField(decimal_places=5, max_digits=24),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price_pcs',
            field=models.DecimalField(decimal_places=5, max_digits=24),
        ),
    ]
