# Generated by Django 4.2 on 2025-06-05 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0006_alter_content_name_alter_content_short_name'),
        ('invoice', '0010_alter_invoiceitem_gross_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('sheet', models.CharField(blank=True, max_length=50, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arrival.container')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='container',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='freight_cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pto',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='station',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms',
        ),
        migrations.AddField(
            model_name='invoice',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='file',
            field=models.FileField(default=1, upload_to='invoices/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arrival.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='prev_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
