# Generated by Django 4.2 on 2025-06-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoicecontainer_remove_invoice_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
