# Generated by Django 4.2 on 2025-06-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0006_alter_content_name_alter_content_short_name'),
        ('invoice', '0012_alter_invoice_create_date_alter_invoice_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='traindoc/')),
                ('prev_file', models.FileField(blank=True, null=True, upload_to='traindoc/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrival.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
