# Generated by Django 4.2 on 2025-06-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrival', '0007_lot_container_lot'),
        ('invoice', '0013_traindoc_delete_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traindoc',
            name='order',
        ),
        migrations.AddField(
            model_name='traindoc',
            name='lot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='arrival.lot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traindoc',
            name='file',
            field=models.FileField(upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='traindoc',
            name='prev_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
