# Generated by Django 4.2 on 2025-06-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_remove_traindoc_order_traindoc_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindoc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
