# Generated by Django 4.2 on 2025-06-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_traindoc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindoc',
            name='sheet_count',
            field=models.IntegerField(default=0),
        ),
    ]
