# Generated by Django 4.2 on 2025-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_traindoc_sheet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecontainer',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
