# Generated by Django 4.2 on 2025-06-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_alter_invoicecontainer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traindoc',
            name='sheet_count',
        ),
    ]
