# Generated by Django 4.2.28 on 2026-03-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0002_scoreboardview'),
        ('onec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onecttnitem',
            name='name',
        ),
        migrations.AddField(
            model_name='onecttnitem',
            name='model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='shtrih.models'),
        ),
    ]
