# Generated by Django 4.2.28 on 2026-04-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0002_scoreboardview'),
        ('onec', '0002_remove_onecttnitem_name_onecttnitem_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onecttnitem',
            name='model',
        ),
        migrations.AddField(
            model_name='onecttnitem',
            name='model_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='shtrih.modelnames'),
        ),
    ]
