# Generated by Django 4.2.28 on 2026-04-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0003_remove_onecttnitem_model_onecttnitem_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecttnitem',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
