# Generated by Django 4.2.28 on 2026-04-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0004_onecttnitem_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecttn',
            name='receiver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
