# Generated by Django 4.2.28 on 2026-05-07 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0002_scoreboardview'),
        ('onec', '0005_onecttn_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecttnitem',
            name='model_name',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='shtrih.modelnames'),
        ),
    ]
