# Generated by Django 4.2.28 on 2026-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0006_alter_onecttnitem_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecttn',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
