# Generated by Django 4.2.28 on 2026-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0007_onecttn_shipment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecttn',
            name='is_bel_receiver',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
