# Generated by Django 4.2.23 on 2026-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreboardView',
            fields=[
                ('shift', models.CharField(db_column='shift', max_length=1)),
                ('module_digit', models.IntegerField(db_column='module_digit')),
                ('work_date', models.DateField(db_column='work_date')),
                ('workplace', models.IntegerField(db_column='workplace')),
                ('quantity', models.IntegerField(db_column='quantity', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'scoreboard_data',
                'ordering': ['module_digit'],
                'managed': False,
            },
        ),
    ]
