# Generated by Django 4.2.23 on 2025-10-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shtrih', '0006_protocols_typesofwork_workplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransitions',
            fields=[
                ('old_product', models.OneToOneField(db_column='old_product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='old_product_transitions', serialize=False, to='shtrih.products')),
            ],
            options={
                'db_table': 'product_transitions',
                'managed': False,
                'auto_created': False,
            },
        ),
    ]
