# Generated by Django 4.2.23 on 2025-11-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('sender', models.CharField(max_length=38)),
                ('sender_address', models.CharField(max_length=250)),
                ('delivery_terms', models.CharField(max_length=10)),
                ('item_count', models.IntegerField()),
                ('receiver', models.CharField(max_length=38)),
                ('receiver_address', models.CharField(max_length=250)),
                ('sender_country_code', models.CharField(max_length=10)),
                ('sender_alpha_country_code', models.CharField(max_length=10)),
                ('g15A_1', models.CharField(max_length=10)),
                ('payment_currency_code', models.CharField(max_length=3)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency_rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('foreign_economic_code', models.CharField(max_length=10)),
                ('payment_type_code', models.CharField(max_length=10)),
                ('provision_date', models.DateField()),
                ('paid_payment_details_count', models.SmallIntegerField()),
                ('declaration_id', models.BigIntegerField(unique=True)),
                ('declaration_number', models.CharField(max_length=18)),
                ('permit_number', models.CharField(max_length=23)),
                ('country_name', models.CharField(max_length=17)),
                ('declarant_position', models.CharField(max_length=250)),
                ('declarant_FIO', models.CharField(max_length=250)),
                ('document_id', models.CharField(max_length=36)),
                ('sender_country_name', models.CharField(max_length=17)),
                ('outgoing_number', models.CharField(max_length=50)),
                ('dollar_rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('euro_rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('declaration_date', models.DateField()),
                ('permit_code', models.CharField(max_length=10)),
                ('gifted', models.BooleanField(default=False)),
                ('is_use', models.BooleanField(default=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='arrival.container')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='G44',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g32', models.IntegerField(blank=True, null=True)),
                ('g44kd', models.CharField(blank=True, max_length=50, null=True)),
                ('g44nd', models.CharField(blank=True, max_length=255, null=True)),
                ('g44dd', models.DateField(blank=True, null=True)),
                ('g44i', models.IntegerField(blank=True, null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g44', to='declaration.declaration', to_field='declaration_id')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='G313',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g32', models.IntegerField(blank=True, null=True)),
                ('g313i', models.IntegerField(blank=True, null=True)),
                ('g31_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_tm', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_pb', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_pm', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_mg', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_sp', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_vg', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_rd', models.DateField(blank=True, null=True)),
                ('g31_qg', models.FloatField(blank=True, null=True)),
                ('g31_nu', models.CharField(blank=True, max_length=50, null=True)),
                ('g31_cu', models.CharField(blank=True, max_length=50, null=True)),
                ('g31_gg', models.TextField(blank=True, null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G313', to='declaration.declaration', to_field='declaration_id')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeclaredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_selected', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.TextField()),
                ('ordinal_number', models.IntegerField()),
                ('country_code', models.CharField(max_length=3)),
                ('alpha_country_code', models.CharField(max_length=3)),
                ('gross_weight', models.FloatField()),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit_code', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('statistical_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('payment_details_count', models.IntegerField()),
                ('document_details_count', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=17)),
                ('g37', models.CharField(max_length=2)),
                ('net_weight', models.FloatField()),
                ('previous_customs_regime_code', models.CharField(max_length=2)),
                ('g373', models.CharField(max_length=3)),
                ('customs_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('items_quantity', models.FloatField(max_length=50)),
                ('measurement_code', models.CharField(max_length=3)),
                ('measurement', models.CharField(max_length=13)),
                ('valuation_method', models.CharField(max_length=2)),
                ('available_quantity', models.FloatField(default=0.0)),
                ('item_code_1c', models.BigIntegerField(blank=True, null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declared_items', to='declaration.declaration')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
