# Generated by Django 4.2.23 on 2025-12-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
