# Generated by Django 4.2.20 on 2025-03-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='G313',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g32', models.IntegerField(blank=True, null=True)),
                ('g313i', models.IntegerField(blank=True, null=True)),
                ('g31_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_tm', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_pb', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_pm', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_mg', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_sp', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_vg', models.CharField(blank=True, max_length=255, null=True)),
                ('g31_rd', models.DateField(blank=True, null=True)),
                ('g31_qg', models.FloatField(blank=True, null=True)),
                ('g31_nu', models.CharField(blank=True, max_length=50, null=True)),
                ('g31_cu', models.CharField(blank=True, max_length=50, null=True)),
                ('g31_gg', models.TextField(blank=True, null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G313', to='declaration.declaration', to_field='declaration_id')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
