# Generated by Django 4.2.20 on 2025-03-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0002_g313'),
    ]

    operations = [
        migrations.CreateModel(
            name='G44',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g32', models.IntegerField(blank=True, null=True)),
                ('g44kd', models.CharField(blank=True, max_length=50, null=True)),
                ('g44nd', models.CharField(blank=True, max_length=255, null=True)),
                ('g44dd', models.DateField(blank=True, null=True)),
                ('g44i', models.IntegerField(blank=True, null=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g44', to='declaration.declaration', to_field='declaration_id')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
