# Generated by Django 4.2.20 on 2025-03-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0003_g44'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='delivery_terms',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='foreign_economic_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='g15A_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='payment_type_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='permit_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='sender_alpha_country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='sender_country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='type_code',
            field=models.CharField(max_length=10),
        ),
    ]
