# Generated by Django 4.2 on 2025-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0004_alter_declaration_delivery_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declareditem',
            name='factory_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='declareditem',
            name='is_selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
