# Generated by Django 4.2.20 on 2025-04-30 07:19

from django.db import migrations, models


def copy_quantity_to_available(apps, schema_editor):
    DeclaredItem = apps.get_model('declaration', 'DeclaredItem')
    for item in DeclaredItem.objects.all():
        # None → 0.0
        avail = item.quantity or 0.0
        DeclaredItem.objects.filter(pk=item.pk).update(available_quantity=avail)


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0004_alter_declaration_delivery_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declareditem',
            name='g31stz',
        ),
        migrations.AddField(
            model_name='declareditem',
            name='available_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='declareditem',
            name='items_quantity',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(copy_quantity_to_available, migrations.RunPython.noop),
    ]
