# Generated by Django 4.2.20 on 2025-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0005_declareditem_factory_code_declareditem_is_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declareditem',
            old_name='g312STZ',
            new_name='measurement',
        ),
        migrations.RenameField(
            model_name='declareditem',
            old_name='g311stz',
            new_name='measurement_code',
        ),
        migrations.RemoveField(
            model_name='declareditem',
            name='g31stz',
        ),
        migrations.AddField(
            model_name='declareditem',
            name='available_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='declareditem',
            name='items_quantity',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
