# Generated by Django 4.2.20 on 2025-04-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0005_remove_declareditem_g31stz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declareditem',
            old_name='g312STZ',
            new_name='measurement',
        ),
        migrations.RenameField(
            model_name='declareditem',
            old_name='g311stz',
            new_name='measurement_code',
        ),
        migrations.AlterField(
            model_name='declareditem',
            name='items_quantity',
            field=models.FloatField(max_length=50),
        ),
    ]
