# Generated by Django 4.2.20 on 2025-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0006_rename_g312stz_declareditem_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declareditem',
            name='item_code_1c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
