# Generated by Django 4.2.20 on 2025-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0007_declareditem_item_code_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declareditem',
            name='item_code_1c',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
