# Generated by Django 4.2.20 on 2025-05-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0008_alter_declareditem_item_code_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declareditem',
            name='name',
            field=models.TextField(),
        ),
    ]
