# Generated by Django 4.2.20 on 2025-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0009_alter_declareditem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='gifted',
            field=models.BooleanField(default=False),
        ),
    ]
