# Generated by Django 4.2.23 on 2025-09-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0010_declaration_gifted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='declaration_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
