# Generated by Django 4.2.23 on 2025-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration', '0011_alter_declaration_declaration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='is_use',
            field=models.BooleanField(default=True),
        ),
    ]
